### ISSUE TITLE
请问能否提供一份docker-compose的容器编排文件？

### ISSUE THREAD

**Issue by Shuazijun** [VaalaCat/frp-panel#50]
如果能推送到1panel应用商店就更好了

**Comment by VaalaCat** [comment]
```yaml
version: '3'

services:
  frp-panel:
    image: vaalacat/frp-panel
    network_mode: host
    restart: unless-stopped
    volumes:
      - /opt/frp-panel:/data
    environment:
      - APP_GLOBAL_SECRET=your_secret # 替换为一串非常长的随机字符
      - MASTER_RPC_HOST=0.0.0.0 # 替换为你的IP
```

**Comment by moreant** [comment]
可以用这个网站转一下 https://www.composerize.com/

**Comment by likesrt** [comment]
-   master
    
```
    services:
      frp-panel:
        image: vaalacat/frp-panel
        container_name: frp-panel
        restart: unless-stopped
        ports:
          - "9000:9000"  # API控制台端口
          - "9001:9001"  # rpc端口
          - "7000:7000"  # frps 端口
          - "20000-20050:20000-20050"  # 给frps预留的端口
        environment:
          - APP_SECRET=dchre# 应用密钥
          - APP_GLOBAL_SECRET=fwgeAPP_GLOBAL_SECRETrge  # Master的secret 全局密钥，用于管理生成密钥，需妥善保管
          - MASTER_RPC_HOST=124.555.33.22  # 服务器的外部IP
          - MASTER_RPC_PORT=9001
          - APP_COOKIE_AGE=864000
          - MASTER_COMPATIBLE_MODE=true # 兼容模式 可使用官方客户端
          
        volumes:
          - ./frp-panel:/data  # 数据存储位置
        labels:
            createdBy: Locals 
    
    或者
    
    services:
      frp-panel:
        image: vaalacat/frp-panel
        container_name: frp-panel
        restart: unless-stopped
        network_mode: host  # 使用主机网络
        volumes:
          - ./frp-panel:/data  # 数据存储位置
        environment:
          - APP_SECRET=dchre # 应用密钥
          - APP_GLOBAL_SECRET=fwgeAPP_GLOBAL_SECRETrge  # Master的secret 全局密钥，用于管理生成密钥，需妥善保管
          - MASTER_RPC_HOST=124.555.33.22# 服务器的外部IP
          - MASTER_RPC_PORT=9001 # RPC端口
          - APP_COOKIE_AGE=864000
          - MASTER_COMPATIBLE_MODE=true # 兼容模式 可使用官方客户端
          - MASTER_API_PORT=9000 # master API端口
          - APP_ENABLE_REGISTER=false # 启用注册true

```

-   server

```

    services:
      frp-panel:
        image: vaalacat/frp-panel
        container_name: frp-panel
        restart: unless-stopped
        network_mode: host  # 使用主机网络
        command:  server -s f62211d684-bgfd-gf5h9-7e965864b843 -i 852.s.tx44test -a frp -r 124.555.33.22 -c 9001 -p 9000 -e http # 启动命令
    

```


-   client

```

    services:
      frp-panel:
        image: vaalacat/frp-panel
        container_name: frp-panel-client
        restart: unless-stopped
        network_mode: host  # 使用主机网络
        command:  client -s f62211d684-bgfd-gf5h9-7e965864b843 -i yuyan.c.test -a frp -r 124.555.33.22 -c 9001 -p 9000 -e http # 启动命令
    


```
